GET http://localhost:5000/users

###
POST http://localhost:5000/users
Content-Type: application/json

{
    "username": "hafiz", 
    "email": "hafiz@gmail.com", 
    "password": "hafiz123",
    "password": "hafiz123",
}